### PR TITLE
More ruby 2.7 `last argument as keyword parameters is deprecated` addressed

### PR DESCRIPTION
**Pull request by DavidS**

### CODE REVIEW

**Review by martin308 — APPROVED** [review]
LGTM, thanks @DavidS!

**Comment by martinandert** [comment]
Hi, any chance you can cut a release with this change? Thanks!

**Comment by MikeGoldsmith** [comment]
Hi @martinandert - we plan on making a release later today 👍

**Comment by paulosman** [comment]
> Hi @martinandert - we plan on making a release later today

One day late, but better late than never! v1.14.7 is out @martinandert

**Pull request merged**
